[meta]
displayName = "Português (Brasil)"

[ejs.landing]
updateAvailableTooltip = "Atualização disponível"
usernamePlaceholder = "Usuário"
usernameEditButton = "Editar"
settingsTooltip = "Configurações"
serverStatus = "SERVIDOR"
serverStatusPlaceholder = "OFFLINE"
mojangStatus = "STATUS MOJANG"
mojangStatusTooltipTitle = "Serviços"
mojangStatusNETitle = "Não&nbsp;Essenciais"
newsButton = "NOTICIAS"
launchButton = "JOGAR"
launchButtonPlaceholder = "&#8226; Nenhum servidor selecionado"
launchDetails = "Aguarde.."
newsNavigationStatus = "{currentPage} de {totalPages}"
newsErrorLoadSpan = "Buscando noticias.."
newsErrorFailedSpan = "Falha ao carregar"
newsErrorRetryButton = "Tentar novamente"
newsErrorNoneSpan = "Sem notícias"

[ejs.loginOptions]
loginOptionsTitle = "Bem-vindo(a)!"
loginWithMicrosoft = "Entrar com Microsoft"
cancelButton = "Cancelar"

[ejs.overlay]
serverSelectHeader = "Servidores disponíveis"
serverSelectConfirm = "Selecionar"
serverSelectCancel = "Cancelar"
accountSelectHeader = "Selecione uma conta"
accountSelectConfirm = "Selecionar"
accountSelectCancel = "Cancelar"

[ejs.settings]
navHeaderText = "Configurações"
navAccount = "Conta"
navMinecraft = "Minecraft"
navMods = "Mods"
navJava = "Java"
navLauncher = "Launcher"
navAbout = "Sobre"
navUpdates = "Atualizações"
navDone = "Concluir"
tabAccountHeaderText = "Configurações da Conta"
tabAccountHeaderDesc = "Adicione novas contas ou gerencie as existentes."
microsoftAccount = "Microsoft"
addMicrosoftAccount = "+ Adicionar Conta Microsoft"
minecraftTabHeaderText = "Configurações do Minecraft"
minecraftTabHeaderDesc = "Opções relacionadas a inicialização do jogo."
gameResolutionTitle = "Resolução do jogo"
launchFullscreenTitle = "Iniciar em tela cheia."
autoConnectTitle = "Conectar automaticamente ao servidor ao iniciar."
launchDetachedTitle = "Executar o jogo separado do launcher."
launchDetachedDesc = "Se o jogo não estiver separado, fechar o launcher tambem fechará o jogo."
tabModsHeaderText = "Configurações de Mods"
tabModsHeaderDesc = "Ative ou desative mods."
switchServerButton = "Trocar"
requiredMods = "Mods obrigatórios"
optionalMods = "Mods opcionais"
dropinMods = "Mods avulsos"
addMods = "Adicionar Mods"
dropinRefreshNote = "(F5 para atualizar)"
shaderpacks = "Shaderpacks"
shaderpackDesc = "Ative ou desative shaders. Lembre-se de que shaders só rodam bem em máquinas mais potentes. Você pode adicionar pacotes personalizados aqui."
selectShaderpack = "Selecionar Shaderpack"
tabJavaHeaderText = "Configurações do Java"
tabJavaHeaderDesc = "Gerencie a configuração do Java (avançado)."
memoryTitle = "Memoria"
maxRAM = "RAM maxima"
minRAM = "RAM minima"
memoryDesc = "O mínimo recomendado de RAM e 3 gigabytes. Definir os valores minimo e maximo como iguais pode reduzir travamentos."
memoryTotalTitle = "Total"
memoryAvailableTitle = "Disponível"
javaExecutableTitle = "Executável do Java"
javaExecSelDialogTitle = "Selecionar executável do Java"
javaExecSelButtonText = "Escolher arquivo"
javaExecDesc = "O executável do Java é válidado antes de iniciar o jogo."
javaPathDesc = "O caminho deve terminar com <strong>{pathSuffix}</strong>."
jvmOptsTitle = "Opções adicionais da JVM"
jvmOptsDesc = "Opções fornecidas para a JVM em tempo de execução. <em>-Xms</em> e <em>-Xmx</em> nao devem ser incluídos."
launcherTabHeaderText = "Configurações do Launcher"
launcherTabHeaderDesc = "Opções relacionadas ao próprio launcher."
allowPrereleaseTitle = "Permitir Atualizações Pre-Release."
allowPrereleaseDesc = "Pre-Releases incluem novos recursos que talvez ainda não tenham sido totalmente testados ou integrados.<br>Isso sempre sera verdadeiro se voce estiver usando uma versão pre-release."
languageTitle = "Idioma"
languageDesc = "Escolha o idioma do launcher. O launcher será recarregado após salvar."
languageLoading = "Carregando idiomas.."
dataDirectoryTitle = "Diretório de dados"
selectDataDirectory = "Selecionar diretório de dados"
chooseFolder = "Escolher pasta"
dataDirectoryDesc = "Todos os arquivos do jogo e instalções locais de Java serão armazenados no diretório de dados.<br>Capturas de tela e mundos salvos ficam na pasta da instância da configuração correspondente do servidor."
aboutTabHeaderText = "Sobre"
aboutTabHeaderDesc = "Veja informações e changelogs da versão atual."
aboutTitle = "{appName}"
stableRelease = "Versão estável"
versionText = "Versão "
sourceGithub = "Código-fonte (GitHub)"
support = "Suporte"
devToolsConsole = "Console DevTools"
releaseNotes = "Notas da versao"
changelog = "Changelog"
noReleaseNotes = "Sem notas de versão"
viewReleaseNotes = "Ver notas da versão no GitHub"
launcherUpdatesHeaderText = "Atualizações do Launcher"
launcherUpdatesHeaderDesc = "Baixe, instale e revise atualizações do launcher."
checkForUpdates = "Verificar Atualizações"
whatsNew = "Novidades"
updateReleaseNotes = "Notas da atualização"

[ejs.waiting]
waitingText = "Aguardando Microsoft.."

[ejs.welcome]
continueButton = "CONTINUAR"

[js.index]
microsoftLoginTitle = "Login Microsoft"
microsoftLogoutTitle = "Logout Microsoft"

[js.login]
login = "ENTRAR"
loggingIn = "ENTRANDO"
success = "SUCESSO"
tryAgain = "Tentar novamente"

[js.login.error]
invalidValue = "* Valor inválido"
requiredValue = "* Obrigatório"

[js.login.error.unknown]
title = "Erro desconhecido durante o login"
desc = "Ocorreu um erro desconhecido. Consulte o console para mais detalhes."

[js.landing.launch]
pleaseWait = "Aguarde.."
failureTitle = "Erro ao iniciar"
failureText = "Veja o console (CTRL + Shift + i) para mais detalhes."
okay = "Ok"

[js.landing.selectedAccount]
noAccountSelected = "Nenhuma conta selecionada"

[js.landing.selectedServer]
noSelection = "Nenhum servidor selecionado"
loading = "Carregando.."

[js.landing.serverStatus]
server = "SERVIDOR"
offline = "OFFLINE"
players = "JOGADORES"

[js.landing.news]
checking = "Buscando noticias"

[js.overlay]
dismiss = "Fechar"

[js.settings.msftLogin]
errorTitle = "Erro no login Microsoft"
errorMessage = "Não foi possivel concluir o login com a Microsoft."
okButton = "Ok"

[js.settings.msftLogout]
errorTitle = "Erro no logout Microsoft"
errorMessage = "Não foi possivel concluir o logout da conta Microsoft."
okButton = "Ok"

[js.settings.authAccountSelect]
selectButton = "Selecionar conta"
selectedButton = "Conta selecionada ✓"

[js.settings.authAccountLogout]
lastAccountWarningTitle = "Remover última conta"
lastAccountWarningMessage = "Está é a ultima conta salva. Se continuar, será necessário fazer login novamente."
confirmButton = "Continuar"
cancelButton = "Cancelar"

[js.settings.authAccountPopulate]
username = "Usuário"
uuid = "UUID"
selectAccount = "Selecionar conta"
selectedAccount = "Conta selecionada ✓"
logout = "Sair"

[js.uicore.autoUpdate]
checkingForUpdateButton = "Verificando Atualizações.."
installNowButton = "Instalar agora"
checkForUpdatesButton = "Verificar Atualizações"
